name: carThings
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - affine=2.4.0=pyhd8ed1ab_1
  - aiofiles=24.1.0=pyhd8ed1ab_1
  - anyio=4.10.0=pyhe01879c_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h163523d_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.5=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=h7dd00d9_1
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - brotli-python=1.1.0=py312h6b01ec3_4
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py312h429097b_1
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - comm=0.2.3=pyhe01879c_0
  - contextily=1.6.2=pyhd8ed1ab_1
  - contourpy=1.3.3=py312ha0dd364_2
  - cpython=3.12.11=py312hd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dash=3.2.0=pyhd8ed1ab_0
  - debugpy=1.8.16=py312he360a15_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - flask=3.1.2=pyhd8ed1ab_0
  - fonttools=4.59.2=py312h6daa0e5_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.0=hce30654_1
  - freexl=2.0.0=h3ab3353_2
  - geographiclib=2.1=pyhd8ed1ab_0
  - geopy=2.4.1=pyhd8ed1ab_2
  - geos=3.14.0=h4bcf65f_0
  - geotiff=1.7.4=h1d7e6e1_2
  - giflib=5.2.2=h93a5062_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=9.5.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json-c=0.18=he4178ee_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312h81bd7bf_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.7=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - kiwisolver=1.4.9=py312hdc12c9d_1
  - krb5=1.21.3=h237132a_0
  - lark=1.2.2=pyhd8ed1ab_1
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libarchive=3.8.1=gpl_h46e8061_100
  - libblas=3.9.0=35_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=35_hb0561ab_openblas
  - libcurl=8.14.1=h73640d1_0
  - libcxx=21.1.0=hf598326_1
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.14.0=hce30654_1
  - libfreetype6=2.14.0=h6da58f4_1
  - libgdal-core=3.10.3=h8bd5561_17
  - libgfortran=15.1.0=hfdf1602_1
  - libgfortran5=15.1.0=hb74de2c_1
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.0=h5505292_0
  - libkml=1.3.0=he250239_1021
  - liblapack=3.9.0=35_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_h60d53f8_2
  - libpng=1.6.50=h280e0eb_1
  - librttopo=1.1.0=hf7cb3ef_19
  - libsodium=1.0.20=h99b78c6_0
  - libspatialite=5.1.0=h67ea1dc_15
  - libsqlite=3.50.4=h4237e3c_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.0=h025e3ab_6
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.8=h4a9ca0c_1
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.0=hbb9b287_0
  - lz4-c=1.10.0=h286801f_1
  - lzo=2.10=h925e9cb_1002
  - markupsafe=3.0.2=py312h998013c_1
  - matplotlib-base=3.10.6=py312h605b88b_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mercantile=1.2.1=pyhd8ed1ab_1
  - minizip=4.0.10=hff1a8ea_0
  - mistune=3.1.4=pyhcf101f3_0
  - msgpack-python=1.1.1=py312ha0dd364_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.5.0=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.4.5=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.3.3=py312h85ea64e_0
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.5.2=he92f556_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - paho-mqtt=2.1.0=pyhe01879c_1
  - pandas=2.3.2=py312h98f7732_0
  - pandas-stubs=2.3.2.250827=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h7125dd6_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py312hce42e9c_1
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - plotly=6.3.0=pyhd8ed1ab_0
  - proj=9.6.2=hdbeaa80_2
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py312h163523d_1
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=11.1=py312h4c66426_1
  - pyobjc-framework-cocoa=11.1=py312h3964663_1
  - pyparsing=3.2.3=pyhe01879c_2
  - pyserial=3.5=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.11=hc22306f_0_cpython
  - python-can=4.6.1=pyhd8ed1ab_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.11=hd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h998013c_2
  - pyzmq=27.1.0=py312hd65ceae_0
  - qhull=2020.2=h420ef59_5
  - rasterio=1.4.3=py312h4623290_1
  - readline=8.2=h1d1bf99_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - retrying=1.4.2=pyhe01879c_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.27.1=py312h6f58b40_1
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hd121638_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlite=3.50.4=hb5dd463_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=pyh31c8845_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_2
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.2=py312h163523d_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312h163523d_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uriparser=0.9.8=h00cdb27_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.3=py312h163523d_1
  - xerces-c=3.2.5=h92fc2f4_2
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstandard=0.24.0=py312h26de6b3_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - ajsonrpc==1.2.0
      - argparse-addons==0.12.0
      - bitstruct==8.21.0
      - bottle==0.13.4
      - cantools==40.5.0
      - chardet==5.2.0
      - click==8.1.7
      - colorama==0.4.6
      - crccheck==1.3.1
      - dash-table==5.0.0
      - diskcache==5.6.3
      - influxdb-client==1.49.0
      - marshmallow==3.26.1
      - platformio==6.1.18
      - pyelftools==0.32
      - reactivex==4.0.4
      - semantic-version==2.10.0
      - starlette==0.46.2
      - tabulate==0.9.0
      - textparser==0.24.0
      - tqdm==4.67.1
      - uvicorn==0.34.3
      - wsproto==1.2.0
prefix: /Users/hz/miniconda3/envs/carThings
